/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetedacy;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ibro_Joe_DIABATE
 */
public class Gestion_des_inscriptions extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_des_inscriptions
     */
    Seconnecter con = new Seconnecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();
    public Gestion_des_inscriptions() {
        initComponents();
        model.addColumn("id");
        model.addColumn("matricule");
        model.addColumn("nom");
        model.addColumn("prenom");
        model.addColumn("dateNaissance");
        model.addColumn("classe");
        model.addColumn("filiations");
        try{
         stm = con.obtenirconnexion().createStatement();
         ResultSet rs = stm.executeQuery("Select * from eleves");
         while(rs.next()){
         model.addRow(new Object[]{rs.getString("id"), rs.getString("matricule"), 
             rs.getString("nom"), rs.getString("prenom"), rs.getString("dateNaissance"),
             rs.getString("classe"), rs.getString("filiations")});
         
         }
       }catch(SQLException e){System.err.println(e);}
        tableau.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void deplace(int i){
    try{
    txtid.setText(model.getValueAt(i, 0).toString());
    txtmatricule.setText(model.getValueAt(i, 1).toString());
    txtnom.setText(model.getValueAt(i, 2).toString());
    txtprenom.setText(model.getValueAt(i, 3).toString());
    txtdatenaissance.setText(model.getValueAt(i, 4).toString());
    txtclasse.setSelectedItem(model.getValueAt(i, 5).toString());
    txtfiliations.setText(model.getValueAt(i, 6).toString());
    
    }catch(Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
    }
    private void afficher (){
     try{
              model.setRowCount(0);
         stm = con.obtenirconnexion().createStatement();
         ResultSet rs = stm.executeQuery("Select * from eleves");
         while(rs.next()){
         model.addRow(new Object[]{rs.getString("id"), rs.getString("matricule"), 
             rs.getString("nom"), rs.getString("prenom"), rs.getString("dateNaissance"),
             rs.getString("classe"), rs.getString("filiations")});
         
         }
       }catch(SQLException e){System.err.println(e);}
        tableau.setModel(model);
     }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtfindparclasse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        txtfiliations = new javax.swing.JTextField();
        txtclasse = new javax.swing.JComboBox<>();
        txtdatenaissance = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtmatricule = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 550));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/57003a56b5f8470651295adb4b7be139-sinal-de-seta-de-atualiza--o-by-vexels.png"))); // NOI18N
        jButton1.setText("MODIFIER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 360, 190, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/depositphotos_131346240-stock-illustration-black-silhouette-of-magnifying-glass.jpg"))); // NOI18N
        jButton2.setText("RECHERCHER PAR CLASSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 420, 340, 40);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/800px_COLOURBOX5735579.jpg"))); // NOI18N
        jButton4.setText("AJOUTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 360, 170, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/88780557-icône-de-corbeille-silhouette-silhouette-dans-un-style-plat-poubelle-avec-recyclage-des-flèches-de-symbol.jpg"))); // NOI18N
        jButton3.setText("SUPPRIMER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(730, 360, 200, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/téléchargé.png"))); // NOI18N
        jButton5.setText("ACTUALISER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(180, 420, 210, 40);

        txtfindparclasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfindparclasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfindparclasseActionPerformed(evt);
            }
        });
        getContentPane().add(txtfindparclasse);
        txtfindparclasse.setBounds(810, 423, 180, 40);

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tableau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableau);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 90, 500, 110);

        txtfiliations.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfiliations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfiliationsActionPerformed(evt);
            }
        });
        getContentPane().add(txtfiliations);
        txtfiliations.setBounds(280, 320, 180, 30);

        txtclasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premiere L1\t\t", "Premiere L2  \t\t ", "Premiere S1 \t\t", "Premiere S2 \t\t", "Seconde L1", "Seconde L2", "Seconde S1", "Seconde S2", "Terminale L1a   \t\t ", "Terminale L1b    \t\t", "Terminale L2a    \t\t\t", "Terminale L2b    \t", "Terminale S1a", "Terminale S1b", "Terminale S2a", "Terminale S2b" }));
        getContentPane().add(txtclasse);
        txtclasse.setBounds(290, 290, 160, 20);

        txtdatenaissance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtdatenaissance);
        txtdatenaissance.setBounds(290, 240, 160, 23);

        txtprenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtprenom);
        txtprenom.setBounds(290, 200, 160, 23);

        txtnom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtnom);
        txtnom.setBounds(290, 160, 160, 23);

        txtmatricule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatriculeActionPerformed(evt);
            }
        });
        getContentPane().add(txtmatricule);
        txtmatricule.setBounds(290, 120, 160, 23);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtid);
        txtid.setBounds(290, 90, 160, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("id :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 25, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Matricule :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 130, 85, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("NOM :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 54, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("PRENOM :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 210, 89, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Date de Naissance :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 250, 150, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Classe :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 290, 59, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Filiations :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 330, 82, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("GESTION DES INSCRIPTIONS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 40, 270, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(1200, 400));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 990, 480);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Ajouter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Modifier");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem3.setText("Supprimer");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            model.setRowCount(0); 
            {
             Rs = stm.executeQuery("Select * from eleves where classe = '"+txtfindparclasse.getText()+"'");
            }while(Rs.next()){
               Object[] eleves = {Rs.getInt(1), Rs.getString(2), Rs.getString(3), Rs.getString(4), Rs.getString(5), Rs.getString(6), Rs.getString(7)};
               model.addRow(eleves);
               if(model.getRowCount() == 0){JOptionPane.showMessageDialog(null,"Liste vide!");
               }else{ 
                   int i = 0; deplace(i);
               }
            }
         }catch(HeadlessException | SQLException e){System.err.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtmatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatriculeActionPerformed

    private void tableauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauMouseClicked
        try{
        int i = tableau.getSelectedRow();
        deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "erreur de deplacement "+e.getLocalizedMessage());}
    }//GEN-LAST:event_tableauMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = txtid.getText();
        String matricule = txtmatricule.getText();
        String nom = txtnom.getText();
        String prenom = txtprenom.getText();
        String datenaissance = txtdatenaissance.getText();
        String classe = txtclasse.getSelectedItem().toString();
        String filiation = txtfiliations.getText();
        String requete = "Insert into eleves (id, matricule, nom, prenom, dateNaissance, classe, filiations)"
                + " VALUES ('"+id+"', '"+matricule+"', '"+nom+"', '"+prenom+"', '"+datenaissance+"', '"+classe+"', '"+filiation+"')";
        try{
         stm.executeUpdate(requete);
         JOptionPane.showMessageDialog(null, "L'étudiant a bien été enregistré !");
            afficher ();
        }catch(HeadlessException | SQLException ex){JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           if(JOptionPane.showConfirmDialog(null, "Confirmez-vous la modification","mofication",
                       JOptionPane.YES_OPTION)== JOptionPane.OK_OPTION){
                       stm.executeUpdate("UPDATE eleves SET matricule = '"+txtmatricule.getText()+"', nom = '"+txtnom.getText()+"', prenom = '"+txtprenom.getText()+
                         "', dateNaissance = '"+txtdatenaissance.getText()+"', classe = '"+txtclasse.getSelectedItem().toString()+"', filiations = '"+txtfiliations.getText()+"' WHERE id = "+txtid.getText());
                       afficher();
           }
       
       }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "Erreure de modification!"+e.getMessage()); System.err.println(e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            if(JOptionPane.showConfirmDialog(null, "Attention! Êtes-vous sûr de vouloir effectuer cette action?","Supprimer élève!", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
                
                if(txtid.getText().length() != 0){
                    stm.executeQuery("Delete from eleves Where id = "+txtid.getText());
                    afficher();
                 } else{ JOptionPane.showMessageDialog(null, "Veuillez saisir le champ id SVP!");}
        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de suppression! \n"+e.getMessage());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtfindparclasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfindparclasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfindparclasseActionPerformed

    private void txtfiliationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfiliationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfiliationsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_inscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_inscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_inscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_inscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Gestion_des_inscriptions().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableau;
    private javax.swing.JComboBox<String> txtclasse;
    private javax.swing.JTextField txtdatenaissance;
    private javax.swing.JTextField txtfiliations;
    private javax.swing.JTextField txtfindparclasse;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmatricule;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
